final project/Controllers/AdminController.cs
using final_project.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using final_project.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace final_project.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

final project/Controllers/NewsController.cs
using final_project.Models;
using Microsoft.AspNetCore.Mvc;
using final_project.ViewModels;


namespace final_project.Controllers
{
    public class NewsController : Controller
    {
        private readonly AppDbContext _context;

        public NewsController(AppDbContext appDbContext)
        {
            _context = appDbContext;
        }

        public IActionResult Index()
        {
            var NewsModel = _context.News.Select(x => new NewsModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Status = x.Status

            }).ToList();
            return View(NewsModel);
        }
        public IActionResult Detail(int id)
        {
            var NewsModel = _context.News.Select(x => new NewsModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Status = x.Status

            }).SingleOrDefault(x => x.Id == id);
            return View(NewsModel);

        }
        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(NewsModel model)
        {
            var News = new News();
            News.Name = model.Name;
            News.Description = model.Description;
            News.Status = model.Status;
            News.CategoryId = model.CategoryId;
            News.CategoryName = model.CategoryName;


            _context.News.Add(News);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            var NewsModel = _context.News.Select(x => new NewsModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Status = x.Status

            }).SingleOrDefault(x => x.Id == id);
            return View(NewsModel);
        }

        [HttpPost]
        public IActionResult Edit(NewsModel model)
        {
            var News = _context.News.SingleOrDefault(x => x.Id == model.Id);
            News.Name = model.Name;
            News.Description = model.Description;
            News.Status = model.Status;

            _context.News.Update(News);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var NewsModel = _context.News.Select(x => new NewsModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Status = x.Status

            }).SingleOrDefault(x => x.Id == id);
            return View(NewsModel);
        }

        [HttpPost]
        public IActionResult Delete(NewsModel model)
        {
            var product = _context.News.SingleOrDefault(x => x.Id == model.Id);
            _context.News.Remove(product);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult ChangeStatus(int id, bool st)
        {
            var News = _context.News.SingleOrDefault(x => x.Id == id);
            News.Status = st;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult IPage()
        {
            var NewsModel = _context.News.Select(x => new NewsModel()
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                Status = x.Status

            }).ToList();
            return View(NewsModel);
        }
    }
}

final project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - final_project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/final_project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">final_project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="IPage">Haberler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Yapılacaklar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                        </li>
                    </ul>
                    <partial name="_loginPartial"   />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - final_project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>